version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    docker:
      - image: circleci/node:8.14.0-jessie
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'sudo npm install'
      - run:
          name: Build App
          command: 'sudo npm run build'
  test:
    docker:
      - image: circleci/node:8.14.0-jessie
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
